require:
  - rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 16

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Layout/EmptyLinesAroundAttributeAccessor:
   Enabled: true

Layout/SpaceAroundMethodCallOperator:
   Enabled: true

Lint/DeprecatedOpenSSLConstant:
   Enabled: true

Lint/MixedRegexpCaptureTypes:
   Enabled: true

Lint/RaiseException:
   Enabled: true

Lint/StructNewOverride:
   Enabled: true

Style/ExponentialNotation:
   Enabled: true

Style/HashEachMethods:
   Enabled: true

Style/HashTransformKeys:
   Enabled: true

Style/HashTransformValues:
   Enabled: true

Style/RedundantFetchBlock:
   Enabled: true

Style/RedundantRegexpCharacterClass:
   Enabled: true

Style/RedundantRegexpEscape:
   Enabled: true

Style/SlicingWithRange:
   Enabled: true

AllCops:
  Exclude:
    - Gemfile
    - config/puma.rb
    - config/environments/*
    - config/application.rb
    - config/initializers/content_security_policy.rb
    - bin/*
    - tmp/*
    - db/schema.rb
    - db/migrate/*
    - node_modules/**/*
    - vendor/**/*
    - test/test_helper.rb
    - app/channels/application_cable/*
