# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 913288e9b72b74e479ca4e3b11d06977fbbd4848c70c623c3ebd9ed315710a839a323b7db7676198052c4ed82ae5e44861c530ca3ffc52a1202346b4d483d18f

test:
  secret_key_base: 288c1c2be57b22b1640329a5b0e69562d6851344edbaacfa36e7c98a45e4b4f30bb5af4a90d5079e9722ed01373237266679d78094aee4725e3dda3ca6d95faf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
